RB-4 Charge cards requests
unit-finance/unit-ruby-sdk pull request #53
Opened 2023-03-13 08:27 UTC by stymoshchuk

2023-04-23 07:37 UTC, AsafPolakovski commented on lib/unit/api_resources/card_resource.rb
> +        def update(request)
missing docs?

2023-04-27 09:48 UTC, Yaellever commented on lib/unit/api_resources/card_resource.rb
> +        def update(request)
@stymoshchuk

2023-05-07 14:44 UTC, nirmaoz requested changes

2023-05-07 14:44 UTC, nirmaoz commented on lib/unit/models/card/create_business_virtual_credit_card_request.rb
> +    # @param limits [Hash] - optional
missing expiryDate param?

2023-05-07 14:44 UTC, nirmaoz commented on lib/unit/models/card/patch_business_virtual_card_request.rb
> +        payload[:data][:attributes].compact!
please consider calling compact on attributes before setting them:

```ruby
"attributes": {
              "address": address,
              "phone": phone,
              "email": email,
              "tags": tags,
              "limits": limits
            }.compact
```

2023-05-07 14:44 UTC, nirmaoz commented on lib/unit/models/card/card.rb
> +      def create_business_credit_card(account_id:, full_name:, date_of_birth:, address:, shipping_address: nil, phone: nil, email: nil, design: nil, additional_embossed_text: nil, idempotency_key: ni
missing expiryDate ?

2023-05-07 14:44 UTC, nirmaoz commented on lib/unit/models/card/create_business_debit_card_request.rb
> +      attr_reader :account_id, :full_name, :date_of_birth, :address, :shipping_address, :phone, :email, :design, :additional_embossed_text, :idempotency_key, :tags, :limits, :print_only_business_name
missing expiryDate ?

2023-05-11 07:49 UTC, nirmaoz approved these changes

2023-05-11 07:50 UTC, merged